// Reexport your entry components here
export { default as Logo } from './assets/logo.svg';
export { default as video } from './assets/vid.mp4';
export { default as twitter } from './assets/twitter.svg';
export { default as linkedin } from './assets/linkedin.svg';
export { default as bg } from './assets/bg1.png';
export { default as email } from './assets/email.svg';
export { default as phone } from './assets/phone.svg';
export { default as RegisterBg} from './assets/registerbg.svg';
export { default as EventBg1} from './assets/Events/image1.png';
export { default as EventBg2} from './assets/Events/image2.png';
export { default as EventBg3} from './assets/Events/image3.png';
export { default as EventBg4} from './assets/Events/image4.png';
export { default as EventBg5} from './assets/Events/image5.png';
export { default as EventBg6} from './assets/Events/image6.png';
export { default as EventBg7} from './assets/Events/image7.png';
export { default as something} from './assets/something.png';
export { default as Between} from './assets/Between.png';
export { default as back1} from './assets/back1.png';
export { default as back2} from './assets/back2.png';
export { default as back3} from './assets/back3.png';
export { default as infinity} from './assets/Infinity.png';
